--Made to not mingle with the main defines.lua file

NDefines.NDiplomacy.NUM_OF_GREAT_POWERS = 15
NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.35
NDefines.NMilitary.LEADER_MAX_PIPS = 8
NDefines.NCountry.IDEA_TO_TECH = -0.005
NDefines.NCountry.LAND_FORCELIMIT_EXTRA_COST_FACTOR = 3
NDefines.NCountry.NAVAL_FORCELIMIT_EXTRA_COST_FACTOR = 6
NDefines.NCountry.ADVISOR_COST_INCREASE_PER_YEAR = 0.0075
NDefines.NMilitary.OVERRUN_FACTOR = 10
NDefines.NMilitary.OVERRUN_FACTOR_CANNOT_LEAVE = 10
NDefines.NEconomy.MIN_ARMY_MAINTENANCE = 0.20
NDefines.NEconomy.LAND_TECH_MAINTENANCE_IMPACT = 0.03		
NDefines.NEconomy.NAVAL_TECH_MAINTENANCE_IMPACT = 0.03			
NDefines.NEconomy.LAND_TECH_MERC_MAINTENANCE_IMPACT = 0.10
NDefines.NCountry.MIN_DEVELOPMENT_FOR_GOV_RANK_2 = 500
NDefines.NCountry.MIN_DEVELOPMENT_FOR_GOV_RANK_3 = 2500		

